#ifndef DEFINITIONS_HPP
#define DEFINITIONS_HPP
#define SCREEN_WIDTH 665
#define SCREEN_HEIGHT 890

//EKRAN STARTOWY
#define SPLASH_SCREEN_TIME 3.0
#define SPLASH_BACKGROUND_FILEPATH "year2.png"
#define SPLASH_SOUND_EFFECT_FILEPATH "won.wav"
//MAIN MENU
#define MAIN_MENU_BACKGROUND_FILEPATH "backgroundForest.png"
#define GAME_TITLE_FILEPATH "zwierzakowo.png"
#define LATAJACA_KROWA_BUTTON_FILEPATH "latajaca_krowa.png"
//LATAJACA KROWA GRA
#define KROWA_BACKGROUND_FILEPATH "backgroundColorGrass.png"

#endif // DEFINITIONS_HPP
