#ifndef DEFINITIONS_HPP
#define DEFINITIONS_HPP
#define SCREEN_WIDTH 665
#define SCREEN_HEIGHT 890

#define SPLASH_SCREEN_TIME 3.0

#define SPLASH_BACKGROUND_FILEPATH "year2.png"


#endif // DEFINITIONS_HPP
